#!/home/samhaug/anaconda2/bin/python

'''
==============================================================================

File Name : map_paths
Purpose : map raypaths colored with traveltimes
Creation Date : 12-09-2017
Last Modified : Mon 18 Sep 2017 04:43:24 PM EDT
Created By : Samuel M. Haugland

==============================================================================
'''

import numpy as np
from matplotlib import pyplot as plt
from sys import argv
from mpl_toolkits.basemap import Basemap


def main():
    datapath = argv[1]
    e_lines = exceptions(datapath)
    a_lines,coord = available(datapath)
    #print 'available: ',int(float(len(a_lines))/3.)
    #print 'excluded: ',len(e_lines)
    a_coord = avail_coords(a_lines,e_lines,coord)
    evla,evlo = stat_event(datapath)
    plot_coords(np.array(coord),evla,evlo)

def plot_coords(slat,slon,rlat,rlon,del_t):
    m = Basemap(projection='cyl')
    xpt, ypt = m(a_coord[:,1],a_coord[:,0])
    m.scatter(xpt,ypt,s=2,c='k',marker='o',lw=0)
    evlo, evla = m(slon,slat)
    m.scatter(xpt,ypt,s=30,c='r',marker='o',lw=1)
    m.drawcoastlines(linewidth=0.5)
    for ii in len(del_t):
        stlo,stla = m(rlon[ii],rlat[ii])
        if del_t[ii] >= 0:
            m.drawgreatcircle(evlo,evla,stlo,stla,
                              linewidth=1,color='r',alpha=del_t[ii]/10.)
        if del_t[ii] < 0:
            m.drawgreatcircle(evlo,evla,stlo,stla,
                              linewidth=1,color='b',alpha=del_t[ii]/10.)
    plt.tight_layout()
    plt.show()

def ray_paths():
    slat = a[:,5]
    slon = a[:,6]
    rlat = a[:,8]
    rlon = a[:,9]
    del_t = a[:,12]
    return slat,slon,rlat,rlon,del_t
main()




