#!/bin/bash
#
# Use this to submit an obspyDMT data request to the PBS scheduler
#
#
#
#


min_depth=0
max_depth=700
preset=0
offset=3600
waveform_format='sac'
#event_catalog='NEIC_USGS'
event_catalog='GCMT_COMBO'
#event_catalog='LOCAL'
#read_catalog='/dept/geology/geo/home/tomo_project/UM_tomo_tools/event_catalog.txt'
min_mag='6.5'
max_mag='7.5'
cha='BHZ'
min_epi=2
max_epi=180

datapath='China'
echo $datapath
MY_CMD="~/anaconda2/bin/obspyDMT 
--datapath $datapath
--data_source 'IRIS'
--net 'IU'
--min_date 2010-01-01
--min_depth $min_depth 
--max_depth $max_depth
--preset $preset
--offset $offset
--min_mag $min_mag
--max_mag $max_mag
--cha \"$cha\"
--min_epi=$min_epi
--max_epi=$max_epi
--waveform_format $waveform_format
--event_catalog $event_catalog
--event_based 
--instrument_correction
--req_parallel 
--req_np 12
--parallel_process 
--process_np 12"
#--syngine 
#--syngine_bg_model iasp91_2s"

#--read_catalog $read_catalog
echo "# Sample PBS for parallel jobs'" > "$datapath"_submit.pbs
echo "#PBS -A seismoproject_fluxod"                >>"$datapath"_submit.pbs
echo "#PBS -q fluxod"                    >>"$datapath"_submit.pbs
echo "#PBS -l qos=flux"                >>"$datapath"_submit.pbs
echo "#PBS -N $datapath"               >>"$datapath"_submit.pbs
echo "#PBS -l nodes=1:ppn=1,pmem=8gb,walltime=200:00:00">>"$datapath"_submit.pbs
echo "#PBS -d ."                       >>"$datapath"_submit.pbs
echo "#PBS -m n"                       >>"$datapath"_submit.pbs
echo "#PBS -V"                         >>"$datapath"_submit.pbs
echo "#PBS -o $datapath.out"           >>"$datapath"_submit.pbs
echo "#PBS -e $datapath.err"           >>"$datapath"_submit.pbs
echo "ulimit -s unlimited "            >>"$datapath"_submit.pbs
echo $MY_CMD >> "$datapath"_submit.pbs
qsub "$datapath"_submit.pbs



