#!/home/samhaug/anaconda2/bin/python

'''
==============================================================================

File Name : metadata_process
Purpose : Add metadata to sac dictionary, need gcarc, az, and baz
Creation Date : 14-08-2017
Last Modified : Mon 14 Aug 2017 01:57:02 PM EDT
Created By : Samuel M. Haugland

==============================================================================
'''

import obspy
from glob import glob
import os
import argparse

def main():
    parser = argparse.ArgumentParser(
                       description='make data_h5')
    parser.add_argument('-c','--comp',metavar='N',type=str,
                        help='Name of phase')
    args = parser.parse_args()
    a = open('info/station_event')
    b = a.readlines(1)[0].split(',')[9]
    year = int(b[0:4])
    month = int(b[4:6])
    day = int(b[6:8])
    hour = int(b[9:11])
    minute = int(b[11:13])
    second = int(b[13:15])
    ev_time = obspy.core.UTCDateTime(year,month,day,hour,minute,second)
    #if args.comp == 'Z':
    print 'Z'
    st_Z = meta_data('processed/*HZ',ev_time)
    st_Z.write('st_Z.h5',format='H5')
    #if args.comp == 'E':
    print 'E'
    st_E = meta_data('processed/*HE',ev_time)
    st_E.write('st_E.h5',format='H5')
    #if args.comp == 'N':
    print 'N'
    st_N = meta_data('processed/*HN',ev_time)
    st_N.write('st_N.h5',format='H5')

def meta_data(stream,ev_time):
    f = 0.0033528106647474805
    st = obspy.read(stream)
    st.interpolate(10)
    st_new = obspy.core.Stream()
    for idx,tr in enumerate(st):
        new_tr = obspy.core.Trace()
        if (tr.stats.endtime-tr.stats.starttime) < 3400:
            st.remove(tr)
            continue

        a = obspy.geodetics.gps2dist_azimuth(tr.stats.sac['evla'],
                                             tr.stats.sac['evlo'],
                                             tr.stats.sac['stla'],
                                             tr.stats.sac['stlo'],f=f)
        tr.stats.sac['baz'] = a[2]
        tr.stats.sac['az'] = a[1]
        tr.stats.sac['gcarc'] = a[0]/111195.
        tr.stats.sac['o'] = ev_time-tr.stats.starttime
        new_tr.stats.evla = tr.stats.sac['evla']
        new_tr.stats.evlo = tr.stats.sac['evlo']
        new_tr.stats.stla = tr.stats.sac['stla']
        new_tr.stats.stlo = tr.stats.sac['stlo']
        new_tr.stats.gcarc = tr.stats.sac['gcarc']
        new_tr.stats.evdp = tr.stats.sac['evdp']
        new_tr.stats.o = tr.stats.sac['o']
        new_tr.stats.az = tr.stats.sac['az']
        new_tr.stats.baz = tr.stats.sac['baz']
        new_tr.stats.stel = tr.stats.sac['stel']
        new_tr.stats.mag = tr.stats.sac['mag']
        new_tr.data = tr.data
        new_tr.stats.network = tr.stats.network
        new_tr.stats.station = tr.stats.station
        new_tr.stats.location = tr.stats.location
        new_tr.stats.channel = tr.stats.channel
        new_tr.stats.starttime = tr.stats.starttime
        new_tr.stats.sampling_rate= tr.stats.sampling_rate
        new_tr.stats.calib = tr.stats.calib
        st_new.append(new_tr)

    return st_new

main()

