#!/home/samhaug/anaconda2/bin/python

'''
==============================================================================

File Name : metadata_process
Purpose : Add metadata to sac dictionary, need gcarc, az, and baz
Creation Date : 14-08-2017
Last Modified : Mon 14 Aug 2017 01:57:02 PM EDT
Created By : Samuel M. Haugland

==============================================================================
'''

import obspy

def main():
    f = 0.0033528106647474805
    st = obspy.read('processed/*')
    for tr in st:
        name = tr.stats.network+'.'+tr.stats.station+'.'+tr.stats.location+'.'+tr.stats.channel
        a = obspy.geodetics.gps2dist_azimuth(tr.stats.sac['evla'],
                                             tr.stats.sac['evlo'],
                                             tr.stats.sac['stla'],
                                             tr.stats.sac['stlo'],f=f)
        tr.stats.sac['baz'] = a[2]
        tr.stats.sac['az'] = a[1]
        tr.stats.sac['gcarc'] = a[0]/111195.
        tr.write('processed/'+name,format='SAC')
main()

