#!/home/samhaug/anaconda2/bin/python

'''
==============================================================================

File Name : h5_to_ascii.py
Purpose : convert h5 pick file to universal ascii file
Creation Date : 27-03-2018
Last Modified : Tue 27 Mar 2018 06:37:14 PM EDT
Created By : Samuel M. Haugland

==============================================================================
'''

import numpy as np
import h5py
import argparse

def main():
    parser = argparse.ArgumentParser(
                       description='Measure and record traveltime delays')
    parser.add_argument('-f','--file',metavar='H5 file',type=str,
                        help='name of h5 pick file')
    parser.add_argument('-c','--coor',default=0.75,type=float,
                        help='minimum correlation coefficient')
    parser.add_argument('-l','--lsq',default=0.75,type=float,
                        help='minimum lsq value')
    args = parser.parse_args()

    c = args.coor
    l = args.lsq
    h5 = h5py.File(args.file,'r')
    out = args.file.split('.')[0]+'.dat'

    with open(out,'w') as f:
        for keys in h5:
            f.write(keys+'\n')
            try:
                for ii in h5[keys]['pick_info'][:]:
                    if float(ii[18]) >= c and float(ii[24]) >= l:
                        evla = ii[2]
                        evlo = ii[3]
                        stla = ii[4]
                        stlo = ii[5]
                        gcarc = ii[6]
                        evdp = ii[8]
                        tobs = ii[10]
                        del_t = str(float(ii[11])+float(ii[12]))
                        f.write('{} {} {} {} {} {} {} {}\n'.format(
                                evla,evlo,stla,stlo,gcarc,evdp,tobs,del_t))
            except KeyError:
                continue

main()
