#!/home/samhaug/anaconda2/bin/python

'''
==============================================================================

File Name : h5_to_ascii.py
Purpose : convert h5 pick file to universal ascii file
Creation Date : 27-03-2018
Last Modified : Tue 27 Mar 2018 06:37:14 PM EDT
Created By : Samuel M. Haugland

==============================================================================
'''

import numpy as np
import h5py
import argparse
import re

def main():
    parser = argparse.ArgumentParser(
                       description='Measure and record traveltime delays')
    parser.add_argument('-f','--file',metavar='H5 file',type=str,
                        help='name of h5 pick file')
    parser.add_argument('-c','--coor',default=0.65,type=float,
                        help='minimum correlation coefficient')
    parser.add_argument('-l','--lsq',default=0.75,type=float,
                        help='minimum lsq value')
    args = parser.parse_args()

    c = args.coor
    l = args.lsq
    h5 = h5py.File(args.file,'r')
    out = args.file.split('.')[0]+'.dat'
    prefix = args.file.split('.')[0]

    evla = float(h5['S40']['pick_info'][:][0,2])
    evlo = float(h5['S40']['pick_info'][:][0,3])
    evdp = float(h5['S40']['pick_info'][:][0,8])
    for keys in h5:
        with open(prefix+'_'+keys) as f:
            try:
                phase = filter(None,re.split(r'(\d+)',keys))
                for idx,ii in enumerate(h5[keys]['pick_info'][:]):
                    if float(ii[18]) >= c and float(ii[24]) >= l:
                        stla = float(ii[4])
                        stlo = float(ii[5])
                        stel = 0
                        gcarc = float(ii[6])
                        tobs = float(ii[10])
                        del_t = float(ii[11])+float(ii[12])
                        f.write(str(idx)+' {:6.3f} {:6.3f} {:6.3f} '
                                '{:6.3f} {:6.3f} {:6.3f} {:6.3f}\n'.format(
                                evla,evlo,evdp,stla,stlo,stel,tobs))
            except KeyError:
                continue

main()



