#!/home/samhaug/anaconda2/bin/python

'''
==============================================================================

File Name : map_events
Purpose : plot events from given timeframe
Creation Date : 12-09-2017
Last Modified : Mon 18 Sep 2017 04:43:24 PM EDT
Created By : Samuel M. Haugland

==============================================================================
'''

import numpy as np
from matplotlib import pyplot as plt
from sys import argv
from mpl_toolkits.basemap import Basemap


def main():
    a = np.genfromtxt('EVENTS-INFO/catalog_table.txt',
                      skip_header=6,skip_footer=1)
    plot_coords(a[:,1:3])

def plot_coords(a_coord):
    m = Basemap(projection='cyl')
    xpt, ypt = m(a_coord[:,1],a_coord[:,0])
    m.scatter(xpt,ypt,s=30,c='r',marker='o',lw=1)
    m.drawcoastlines(linewidth=0.5)
    plt.tight_layout()
    plt.show()


main()




