#!/home/samhaug/anaconda2/bin/python

'''
==============================================================================

File Name : map_events
Purpose : plot events from given timeframe
Creation Date : 12-09-2017
Last Modified : Mon 18 Sep 2017 04:43:24 PM EDT
Created By : Samuel M. Haugland

==============================================================================
'''

import numpy as np
from matplotlib import pyplot as plt
from sys import argv
from glob import glob
from mpl_toolkits.basemap import Basemap


def main():
    m = Basemap(projection='cyl')
    ax = plt.gca()
    m.drawcoastlines(linewidth=0.5)
    dirlist = glob(argv[1])
    for jj in dirlist:
        try:
            a = open(jj+'/EVENTS-INFO/catalog_table.txt').readlines()[6:-1]
            for ii in a:
                lat,lon = float(ii.strip().split()[1]),float(ii.strip().split()[2])
                xpt, ypt = m(lon,lat)
                m.scatter(xpt,ypt,s=30,c='r',marker='o',lw=1)
                ax.annotate(str(ii.strip().split()[7]),(xpt,ypt),xytext=(5,5),
                            textcoords='offset points')
        except IOError:
            continue

    plt.tight_layout()
    plt.show()


main()




