#!/home/samhaug/anaconda2/bin/python

'''
==============================================================================

File Name : map_Sdiff
Purpose : map Sdiff traveltimes from h5 data_file
Creation Date : 12-09-2017
Last Modified : Mon 18 Sep 2017 04:43:24 PM EDT
Created By : Samuel M. Haugland

==============================================================================
'''

import numpy as np
from obspy.geodetics.base import gps2dist_azimuth
import geopy
from geopy.distance import VincentyDistance
from matplotlib import pyplot as plt
from mpl_toolkits.basemap import Basemap
import argparse
import h5py
from glob import glob


def main():
    parser = argparse.ArgumentParser(
                       description='map S times')
    parser.add_argument('-f','--h5_files',metavar='*picks.h5',type=str,
                        help='list of h5_files')
    parser.add_argument('-l','--max_dist',metavar='float',type=float,
                        default=180,help='maximum_distance (deg)')
    parser.add_argument('-s','--min_dist',metavar='float',type=float,
                        default=0,help='minimum distance (deg)')

    args = parser.parse_args()
    fig,ax = plt.subplots()
    dat_list = glob(args.h5_files)
    m = Basemap(projection='mbtfpq',lon_0=180,resolution='c')
    m.drawparallels(np.arange(-90.,120.,30.))
    m.drawmeridians(np.arange(0.,360.,60.))
    m.drawcoastlines()
    s5_total = 0
    s10_total = 0
    s20_total = 0
    s40_total = 0
    sdiff15_total = 0
    sdiff30_total = 0
    for ii in dat_list:
        print ii
        h5f = h5py.File(ii,'r',driver='core')
        s5_total += list_plot(h5f,m,s5_total,'S5',args)
        s10_total += list_plot(h5f,m,s10_total,'S10',args)
        s20_total += list_plot(h5f,m,s20_total,'S20',args)
        s40_total += list_plot(h5f,m,s40_total,'S40',args)
        sdiff15_total += list_plot(h5f,m,sdiff15_total,'Sdiff15',args)
        sdiff30_total += list_plot(h5f,m,sdiff30_total,'Sdiff30',args)
    print 's5 total: ', s5_total
    print 's10 total: ', s10_total
    print 's20 total: ', s20_total
    print 's40 total: ', s40_total
    print 'sdiff15 total: ', sdiff15_total
    print 'sdiff30 total: ', sdiff30_total
    plt.tight_layout()
    plt.show()

def list_plot(h5f,m,total,name,args):
    try:
        s_dat = h5f[name]['pick_info'][:]
    except KeyError:
        return 0
    s_del = np.array([float(ii) for ii in s_dat[:,11]])
    slat = np.array([float(ii) for ii in s_dat[:,2]])
    slon = np.array([float(ii) for ii in s_dat[:,3]])
    rlat = np.array([float(ii) for ii in s_dat[:,4]])
    rlon = np.array([float(ii) for ii in s_dat[:,5]])
    gcarc = np.array([float(ii) for ii in s_dat[:,6]])
    #print 'Measurements: ', len(s_del)
    for ii in range(len(slat)):
        if gcarc[ii] <= args.max_dist and gcarc[ii] >= args.min_dist:
            plot_coords(m,slat[ii],slon[ii],rlat[ii],rlon[ii],s_del[ii])
        else:
            continue
    lon,lat = m(slon[0],slat[0])
    m.scatter(lon,lat,color='k',s=80,marker='D')
    return len(s_del)

def plot_coords(m,slat,slon,rlat,rlon,del_t):
    stlo,stla = m(rlon,rlat)
    bearing = gps2dist_azimuth(slat,slon,rlat,rlon)[1]
    dist = gps2dist_azimuth(slat,slon,rlat,rlon)[0]/2000.
    origin = geopy.Point(slat,slon)
    destination = VincentyDistance(kilometers=dist).destination(origin,bearing)
    lon,lat = m(destination[1],destination[0])
    if abs(del_t) <= 2:
        size = 10
    if 2 < abs(del_t) and abs(del_t) <= 4:
        size = 20
    if 4 < abs(del_t) and abs(del_t) <= 6:
        size = 30
    if 6 < abs(del_t) and abs(del_t) <= 8:
        size = 40
    if 8 < abs(del_t) and abs(del_t) <= 10:
        size = 50
    if 10 < abs(del_t) and abs(del_t) <= 12:
        size = 60
    if abs(del_t) > 12:
        size = 70
    if del_t <= 0:
        color = 'blue'
        marker = 'o'
        facecolor='none'
    if del_t > 0:
        color = 'red'
        marker = 'x'
        facecolor='red'
    m.scatter(lon,lat,linewidth=1,color=color,alpha=0.6,
              s=1.5*size,marker=marker,facecolor=facecolor)

main()

