#!/home/samhaug/anaconda2/bin/python

'''
==============================================================================

File Name : map_paths
Purpose : map raypaths colored with traveltimes
Creation Date : 12-09-2017
Last Modified : Mon 18 Sep 2017 04:43:24 PM EDT
Created By : Samuel M. Haugland

==============================================================================
'''

import numpy as np
from matplotlib import pyplot as plt
from sys import argv
from mpl_toolkits.basemap import Basemap


def main():
    slat,slon,rlat,rlon,del_t = ray_paths(argv[1])
    plot_coords(slat,slon,rlat,rlon,del_t)

def plot_coords(slat,slon,rlat,rlon,del_t):
    m = Basemap(projection='cyl')
    m.drawcoastlines()
    for ii in range(len(del_t)):
        stlo,stla = m(rlon[ii],rlat[ii])
        if del_t[ii] >= 0:
            m.drawgreatcircle(slon[ii],slat[ii],rlon[ii],rlat[ii],
                              linewidth=1,color='r',alpha=del_t[ii]/10.)
        if del_t[ii] < 0:
            m.drawgreatcircle(slon[ii],slat[ii],rlon[ii],rlat[ii],
                              linewidth=1,color='b',alpha=del_t[ii]/10.)
    plt.tight_layout()
    plt.show()

def ray_paths(fname):
    a = np.genfromtxt(fname,skip_header=210)
    slat = a[:,6]
    slon = a[:,7]
    rlat = a[:,9]
    rlon = a[:,10]
    del_t = a[:,13]
    return slat,slon,rlat,rlon,del_t
main()




