#!/home/samhaug/anaconda2/bin/python

'''
==============================================================================

File Name : rotate_synth
Purpose : rotate to SH component on synthetics
Creation Date : 14-08-2017
Last Modified : Mon 14 Aug 2017 01:57:02 PM EDT
Created By : Samuel M. Haugland

==============================================================================
'''

import numpy as np
from subprocess import call
import os
import obspy
from sys import argv
from glob import glob
from matplotlib import pyplot as plt

def main():
    el = []
    nl = []
    ste = obspy.read('sts_E.h5')
    stn = obspy.read('sts_N.h5')
    i = min(len(ste),len(stn))
    stt = obspy.core.Stream()
    str = obspy.core.Stream()
    for ii in range(0,i):
        name = ste[ii].stats.station+ste[ii].stats.network
        for tr in stn:
            if tr.stats.station+tr.stats.network == name:
                trt = tr.copy()
                trr = tr.copy()
                trt.stats.channel = 'BHT'
                trr.stats.channel = 'BHR'
                trt.stats.o = 0
                trr.stats.o = 0
                e = ste[ii].data
                n = tr.data
                ba = ste[ii].stats.baz
                tdat = e*np.cos(np.radians(ba+180))-n*np.sin(np.radians(ba+180))
                rdat = e*np.sin(np.radians(ba+180))+n*np.cos(np.radians(ba+180))
                trt.data = tdat
                trr.data = rdat
                stt.append(trt)
                str.append(trr)
            else:
                continue
    stt.write('sts_T.h5',format='H5')
    str.write('sts_R.h5',format='H5')

main()

