#!/home/samhaug/anaconda2/bin/python

'''
==============================================================================

File Name : rotate_data
Purpose : rotate to SH component on data
Creation Date : 14-08-2017
Last Modified : Mon 14 Aug 2017 01:57:02 PM EDT
Created By : Samuel M. Haugland

==============================================================================
'''

import numpy as np
from subprocess import call
import os
import obspy
from obspy.signal.rotate import rotate_ne_rt
from sys import argv
from glob import glob
from matplotlib import pyplot as plt

def main():
    el = []
    nl = []
    ste = obspy.read('st_E.h5')
    stn = obspy.read('st_N.h5')
    for tr in ste:
        tr.stats.name = tr.stats.station+tr.stats.network+tr.stats.location
        el.append(tr.stats.name)
    for tr in stn:
        tr.stats.name = tr.stats.station+tr.stats.network+tr.stats.location
        nl.append(tr.stats.name)
    i = set(nl).intersection(set(el))
    for tr in stn:
        if tr.stats.name not in i:
            stn.remove(tr)
    for tr in ste:
        if tr.stats.name not in i:
            ste.remove(tr)
    stn.sort(['name'])
    ste.sort(['name'])
    stt = obspy.core.Stream()
    str = obspy.core.Stream()
    print len(ste)
    print len(stn)
    for ii,tr in enumerate(stn):
        o_mis = np.round(np.abs(tr.stats.o-ste[ii].stats.o),2)
        st_mis = np.round(np.abs(tr.stats.starttime-ste[ii].stats.starttime),2)
        if o_mis-st_mis > 0.1:
            print('o_time not equal to st misfit')
            continue
        else:
            trt = tr.copy()
            trr = tr.copy()
            trt.stats.channel = 'BHT'
            trr.stats.channel = 'BHR'
            e = ste[ii].data
            n = tr.data
            ba = ste[ii].stats.baz
            lim = min(len(e),len(n))
            e = e[::lim]
            n = n[::lim]
            rdat,tdat = rotate_ne_rt(n,e,stn[idx].stats.baz)
            trt.data = tdat
            trr.data = rdat
            stt.append(trt)
            str.append(trr)
    stt.write('st_T.h5',format='H5')
    str.write('st_R.h5',format='H5')

main()

