#!/home/samhaug/anaconda2/bin/python

'''
==============================================================================

File Name : rotate_data
Purpose : rotate to SH component on data
Creation Date : 14-08-2017
Last Modified : Mon 14 Aug 2017 01:57:02 PM EDT
Created By : Samuel M. Haugland

==============================================================================
'''

import numpy as np
from subprocess import call
import os
import obspy
from obspy.signal.rotate import rotate_ne_rt
from sys import argv
from glob import glob
from matplotlib import pyplot as plt

def main():
    otime_misfit = 0
    e_n_mismatch= 0
    el = []
    nl = []
    ste = obspy.read('st_E.h5')
    stn = obspy.read('st_N.h5')
    for tr in ste:
        tr.stats.name = tr.stats.station+tr.stats.network+tr.stats.location
        el.append(tr.stats.name)
    for tr in stn:
        tr.stats.name = tr.stats.station+tr.stats.network+tr.stats.location
        nl.append(tr.stats.name)
    i = set(nl).intersection(set(el))
    for tr in stn:
        if tr.stats.name not in i:
            stn.remove(tr)
    for tr in ste:
        if tr.stats.name not in i:
            ste.remove(tr)
    stn.sort(['name'])
    ste.sort(['name'])
    stt = obspy.core.Stream()
    st_r = obspy.core.Stream()
    if len(stn) != len(ste):
        print('len stn != len ste')
    for ii,tr in enumerate(stn):
        o_mis = np.round(tr.stats.o-ste[ii].stats.o,2)
        st_mis = np.round(tr.stats.starttime-ste[ii].stats.starttime,2)
        if -1*o_mis != st_mis:
            otime_misfit += 1
            continue
        else:
            trt = tr.copy()
            trr = tr.copy()
            trt.stats.channel = 'BHT'
            trr.stats.channel = 'BHR'
            e = ste[ii].data
            n = tr.data
            ba = ste[ii].stats.baz
            if np.abs(len(e)-len(n)) > 200:
                e_n_mismatch += 1
                continue
            else:
                lim = min(len(e),len(n))
                e = e[0:lim]
                n = n[0:lim]
                rdat,tdat = rotate_ne_rt(n,e,stn[ii].stats.baz)
                trt.data = tdat
                trr.data = rdat
                stt.append(trt)
                st_r.append(trr)
    print(str(otime_misfit)+' origin time misfits')
    print(str(e_n_mismatch)+' n e mismatches')
    stt.write('st_T.h5',format='H5')
    st_r.write('st_R.h5',format='H5')


main()

