#!/bin/bash
#
# Use this to process and store h5 data from event
#

#--read_catalog $read_catalog
name=$1_process
echo "# Sample PBS for parallel jobs'" > "$name"_submit.pbs
echo "#PBS -A seismoproject_fluxod"                >>"$name"_submit.pbs
echo "#PBS -q fluxod"                    >>"$name"_submit.pbs
echo "#PBS -l qos=flux"                >>"$name"_submit.pbs
echo "#PBS -N $name"               >>"$name"_submit.pbs
echo "#PBS -l nodes=1:ppn=1,pmem=8gb,walltime=10:00:00">>"$name"_submit.pbs
echo "#PBS -d ."                       >>"$name"_submit.pbs
echo "#PBS -m n"                       >>"$name"_submit.pbs
echo "#PBS -V"                         >>"$name"_submit.pbs
echo "#PBS -o $name.out"           >>"$name"_submit.pbs
echo "#PBS -e $name.err"           >>"$name"_submit.pbs
echo "ulimit -s unlimited "            >>"$name"_submit.pbs
echo "h5_pickle"  >> "$name"_submit.pbs
qsub "$name"_submit.pbs



