#!/bin/bash

#--read_catalog $read_catalog
echo "# Sample PBS for parallel jobs'" > "$datapath"_submit.pbs
echo "#PBS -A seismoproject_fluxod"    >>"$datapath"_submit.pbs
echo "#PBS -q fluxod"                  >>"$datapath"_submit.pbs
echo "#PBS -l qos=flux"                >>"$datapath"_submit.pbs
echo "#PBS -N clean_up"                >>"$datapath"_submit.pbs
echo "#PBS -l nodes=1:ppn=1,pmem=8gb,walltime=1:00:00">>"$datapath"_submit.pbs
echo "#PBS -d ."                       >>"$datapath"_submit.pbs
echo "#PBS -m n"                       >>"$datapath"_submit.pbs
echo "#PBS -V"                         >>"$datapath"_submit.pbs
echo "ulimit -s unlimited"             >>"$datapath"_submit.pbs
echo "rm -rf raw"   >>"$datapath"_submit.pbs
echo "rm -rf resp"  >>"$datapath"_submit.pbs
echo "rm st_E.h5"   >>"$datapath"_submit.pbs
echo "rm sts_E.h5"  >>"$datapath"_submit.pbs
echo "rm st_N.h5"   >>"$datapath"_submit.pbs
echo "rm sts_N.h5"  >>"$datapath"_submit.pbs
echo "rm *.err"  >>"$datapath"_submit.pbs
echo "rm *.out"  >>"$datapath"_submit.pbs
echo "rm *.e"  >>"$datapath"_submit.pbs
echo "rm *.o"  >>"$datapath"_submit.pbs
qsub "$datapath"_submit.pbs
