#!/bin/bash
#
# Use this to submit an obspyDMT data request to the PBS scheduler
#
#
#
#

date=$1

if [ $2 == 1 ]; then
    echo 'January'
    min_date=$date-01-01
    max_date=$date-02-01
elif [ $2 == 2 ]; then
    echo 'February'
    min_date=$date-02-02
    max_date=$date-03-01
elif [ $2 == 3 ]; then
    echo 'March'
    min_date=$date-03-02
    max_date=$date-04-01
elif [ $2 == 4 ]; then
    echo 'April'
    min_date=$date-04-02
    max_date=$date-05-01
elif [ $2 == 5 ]; then
    echo 'May'
    min_date=$date-05-02
    max_date=$date-06-01
elif [ $2 == 6 ]; then
    echo 'June'
    min_date=$date-06-02
    max_date=$date-07-01
elif [ $2 == 7 ]; then
    echo 'July'
    min_date=$date-07-02
    max_date=$date-08-01
elif [ $2 == 8 ]; then
    echo 'August'
    min_date=$date-08-02
    max_date=$date-09-01
elif [ $2 == 9 ]; then
    echo 'September'
    min_date=$date-09-02
    max_date=$date-10-01
elif [ $2 == 10 ]; then
    echo 'October'
    min_date=$date-10-02
    max_date=$date-11-01
elif [ $2 == 11 ]; then
    echo 'November'
    min_date=$date-11-02
    max_date=$date-12-01
elif [ $2 == 12 ]; then
    echo 'December'
    min_date=$date-12-02
    min_date=$date-12-31
    #max_date=$(($date+1))-01-01
fi

min_depth=0
max_depth=700
preset=0
offset=3600
waveform_format='sac'
#event_catalog='NEIC_USGS'
event_catalog='GCMT_COMBO'
#event_catalog='LOCAL'
#read_catalog='/dept/geology/geo/home/tomo_project/UM_tomo_tools/event_catalog.txt'
min_mag='6.2'
max_mag='7.2'
cha='BHE,BHN,BHZ,BH1,BH2'
min_epi=2
max_epi=180

datapath=$date"_"$2
echo $datapath
MY_CMD="~/anaconda2/bin/obspyDMT 
--datapath $datapath
--data_source 'BGR,ETH,GEONET,GFZ,INGV,IPGP,IRIS,ISC,KOERI,LMU,NCEDC,NIEP,NOA,ODC,ORFEUS,RESIF,SCEDC,USP'
--min_date $min_date 
--max_date $max_date 
--min_depth $min_depth 
--max_depth $max_depth
--preset $preset
--offset $offset
--min_mag $min_mag
--max_mag $max_mag
--cha \"$cha\"
--min_epi=$min_epi
--max_epi=$max_epi
--waveform_format $waveform_format
--event_catalog $event_catalog
--event_based 
--instrument_correction
--req_parallel 
--req_np 8
--parallel_process 
--process_np 8
--syngine 
--syngine_bg_model iasp91_2s"

#--read_catalog $read_catalog
echo "# Sample PBS for parallel jobs'" > "$datapath"_submit.pbs
echo "#PBS -A seismoproject_fluxod"                >>"$datapath"_submit.pbs
echo "#PBS -q fluxod"                    >>"$datapath"_submit.pbs
echo "#PBS -l qos=flux"                >>"$datapath"_submit.pbs
echo "#PBS -N $datapath"               >>"$datapath"_submit.pbs
echo "#PBS -l nodes=1:ppn=1,pmem=4gb,walltime=200:00:00">>"$datapath"_submit.pbs
echo "#PBS -d ."                       >>"$datapath"_submit.pbs
echo "#PBS -m n"                       >>"$datapath"_submit.pbs
echo "#PBS -V"                         >>"$datapath"_submit.pbs
echo "#PBS -o $datapath.out"           >>"$datapath"_submit.pbs
echo "#PBS -e $datapath.err"           >>"$datapath"_submit.pbs
echo "ulimit -s unlimited "            >>"$datapath"_submit.pbs
echo $MY_CMD >> "$datapath"_submit.pbs
qsub "$datapath"_submit.pbs



