#!/home/samhaug/anaconda2/bin/python

'''
==============================================================================

File Name : synth_metadata
Purpose : copy sac metadata from processed data to synthetics
Creation Date : 14-08-2017
Last Modified : Mon 14 Aug 2017 01:57:02 PM EDT
Created By : Samuel M. Haugland

==============================================================================
'''

import numpy as np
from subprocess import call
from os import listdir,mkdir
import obspy
from sys import argv

def main():
    mkdir('unused_synth')
    stat = listdir('processed/')
    syn = listdir('syngine_iasp91_2s')
    move = set(syn)-set(stat)
    for ii in move:
        call('mv syngine_iasp91_2s/'+ii+' unused_synth/',shell=True)


    for ii in stat:
        try:
            std = obspy.read('processed/'+ii)
            sts = obspy.read('syngine_iasp91_2s/'+ii)
            sts[0].stats.sac = std[0].stats.sac.copy()
            sts.write('syngine_iasp91_2s/'+ii,format='SAC')
        except IOError:
            continue
main()

