#!/home/samhaug/anaconda2/bin/python

'''
==============================================================================

File Name : travel_time_compute.py
Purpose : Measure and record traveltime delays
Creation Date : 12-09-2017
Last Modified : Wed 27 Sep 2017 04:18:24 PM EDT
Created By : Samuel M. Haugland

==============================================================================
'''

from numpy import round,argmax,max,abs,linspace,roll,pi,hstack,transpose,savetxt,mean,nan_to_num,zeros
from numpy.fft import fft,fftfreq
from os import listdir,getcwd
from matplotlib import pyplot as plt
import matplotlib.gridspec as gridspec
import obspy
from scipy.signal import correlate,butter,freqs
import argparse
from obspy.taup import TauPyModel
import time
model = TauPyModel(model='iasp91')


def main():
    parser = argparse.ArgumentParser(
                       description='Measure and record traveltime delays')
    parser.add_argument('-p','--phase',metavar='N',type=str,
                        help='Name of phase')
    parser.add_argument('-w','--window',default=30,type=int,
                        help='Half of the window length')
    parser.add_argument('--fmin',default=1./100,type=float,
                        help='Minimum frequency')
    parser.add_argument('--fmax',default=1./5,type=float,
                        help='Maximum frequency')
    parser.add_argument('-d','--data',type=str,
                        help='Path to data pickle')
    parser.add_argument('-s','--synth',type=str,
                        help='Path to synthetic pickle')
    parser.add_argument('--stride',default=1,type=int,
                        help='Use every Nth trace in stream')
    parser.add_argument('--plot',dest='plot',
                        action='store_true',help='Plot waveforms')
    args = parser.parse_args()
    fname = write_header(args.phase,args)
    #amp_fname = write_amp_header(args.phase,args.fmin,args.fmax)
    branch_list = phase_info(args.phase)
    write_branch(fname,branch_list)
    write_f_resp(fname,args.fmin,args.fmax)
    std,sts = read_streams(args.data,args.synth)
    welcome_message(args,std)
    std,sts = phase_range(std,sts,args.phase)
    std.filter('bandpass',freqmin=args.fmin,freqmax=args.fmax,zerophase=True)
    sts.filter('bandpass',freqmin=args.fmin,freqmax=args.fmax,zerophase=True)
    now = time.time()
    i = 0
    for idx,ii in enumerate(range(0,len(std),args.stride)):
        total = len(range(0,len(std),args.stride))
        print '{}%'.format(round(float(idx)/total*100.))
        try:
            tobs,corcoeft,\
            m1,m2,update_m1,\
            update_m2,s_amp,\
            d_amp,del_t,key,\
            SNR,amp_rat=\
            find_ttime(
            std[ii],sts[ii],[args.phase],
            (-1*args.window,args.window),args.plot,args)
        except ValueError:
            continue
        if key == 'escape':
            break
        if key == 'alt':
            continue
        if nan_to_num(min(SNR)) < 1.5 or nan_to_num(corcoeft[1]) < 0.75 or nan_to_num(amp_rat) < 0.14:
            continue
        if nan_to_num(max(SNR)) > 15000 or nan_to_num(corcoeft[1]) > 1.5 or nan_to_num(amp_rat) > 7:
            continue
        if key == 'control':
            #write_traveltime(fname,std[ii],1.0,tobs,corcoeft,1.0,args.window,0)
            write_amplitude(fname,ii,std[ii],
                            tobs,corcoeft,
                            m1,m2,
                            update_m1,update_m2,
                            s_amp,d_amp,
                            del_t,SNR,amp_rat)
            i += 1
        else:
            print('control to keep')
            print('alt to discard')
            print('esc to leave')

    then = time.time()
    rate = (len(std)/args.stride)/(then-now)
    print 'Total time: {} sec\n'.format(then-now)
    print 'Your rate: {} traces/sec\n'.format(rate)
    print '{} Proposed picks\n'.format(idx)
    print '{} Accepted picks\n'.format(i)

def welcome_message(args,st):
    print('#######################################')
    print('Computing and recording traveltime delays')
    print('#######################################')
    print 'Data file: ',args.data
    print 'Synthetic file: ',args.synth
    print 'Number of traces: ',len(st)
    print 'Measuring delay of phase ',args.phase
    print 'Event depth: {}km'.format(str(st[0].stats.evdp))
    print 'Phase window is {} seconds long'.format(2*args.window)
    print 'Butterworth filter from {} Hz to {} Hz'.format(args.fmin,args.fmax)
    print 'Using every {} traces'.format(args.stride)
    if args.plot:
        print('Plotting is on')
    if args.plot != True:
        print('Plotting is off')
    print('#######################################')

def npcorr(s,d,samp):
    correl = correlate(s,d,mode='same')
    ts = round((len(d)/2.-argmax(correl))/samp,2)
    return ts

def find_ttime(data_tr,synth_tr,phase,window_tuple,plot,args):
    samp = data_tr.stats.sampling_rate
    d_o = data_tr.stats.o
    d_st = data_tr.stats.starttime
    d_et = data_tr.stats.endtime
    s_o = synth_tr.stats.o
    s_st = synth_tr.stats.starttime
    s_et = synth_tr.stats.endtime

    if phase[0].startswith('S'):
        itime = model.get_travel_times(source_depth_in_km=data_tr.stats.evdp,
                              distance_in_degree=data_tr.stats.gcarc,
                              phase_list=['tts'])[0].time
    if phase[0] == 'P':
        itime = model.get_travel_times(source_depth_in_km=data_tr.stats.evdp,
                              distance_in_degree=data_tr.stats.gcarc,
                              phase_list=['ttp'])[0].time

    time = model.get_travel_times(source_depth_in_km=data_tr.stats.evdp,
                              distance_in_degree=data_tr.stats.gcarc,
                              phase_list=phase)[0].time

    n1 = data_tr.slice(d_st+itime+d_o-200,
                       d_st+itime+d_o-100).data
    n2 = data_tr.slice(d_st+itime+d_o-100,
                       d_st+itime+d_o-50).data
    n3 = data_tr.slice(d_st+itime+d_o-270,
                       d_st+itime+d_o-30).data
    d = data_tr.slice(d_st+time+d_o+window_tuple[0],
                      d_st+time+d_o+window_tuple[1]).data
    s = synth_tr.slice(s_st+time+s_o+window_tuple[0],
                       s_st+time+s_o+window_tuple[1]).data

    t = linspace(window_tuple[0],window_tuple[1],num=len(d))
    T = (1./args.fmax)*1.5
    SNR_1 = round((max(d)-min(d))/(max(n1)-min(n1)),2)
    SNR_2 = round((max(d)-min(d))/(max(n2)-min(n2)),2)
    SNR_3 = round((max(d)-min(d))/(max(n3)-min(n3)),2)
    SNR = (SNR_1,SNR_2,SNR_3)
    s_amp = (max(s)-min(s))
    d_amp = (max(d)-min(d))
    amp_rat = round(s_amp/d_amp,2)
    #First correlation
    del_t = npcorr(s,d,samp)
    roll_s = roll(s,int(samp*del_t))
    mid = int(len(s)/2.)
    cs  = s[mid-int(samp*T):mid+int(samp*T)]
    cd  = d[mid+int(samp*(del_t-T)):mid+int(samp*(del_t+T))]
    #Second correlation
    update_t = npcorr(cs,cd,samp)
    update_cs = roll(cs,int(samp*update_t))

    tcs = linspace(int(-T),int(T),num=len(cs))
    tcd = linspace(int(-T),int(T),num=len(cd))
    m1 = round(max(correlate(cd,cs))/max(correlate(cs,cs)),3)
    m2 = round(max(correlate(cd,cd))/max(correlate(cd,cs)),3)
    update_m1 = round(max(correlate(cd,update_cs))/max(correlate(update_cs,update_cs)),3)
    update_m2 = round(max(correlate(cd,cd))/max(correlate(cd,update_cs)),3)
    corcoeft_1 = round(1-((m2-m1)/m2),3)
    corcoeft_2 = round(1-((update_m2-update_m1)/update_m2),3)
    tobs = del_t+update_t+time
    corcoeft = (corcoeft_1,corcoeft_2)

    if plot == True:
        if phase[0].startswith('S'):
            ds_time = model.get_travel_times(source_depth_in_km=data_tr.stats.evdp,
                              distance_in_degree=data_tr.stats.gcarc,
                              phase_list=['s'+phase[0]])[0].time
            dp_time = 0
        if phase[0] == 'P':
            dp_time = model.get_travel_times(source_depth_in_km=data_tr.stats.evdp,
                              distance_in_degree=data_tr.stats.gcarc,
                              phase_list=['p'+phase[0]])[0].time
            ds_time = model.get_travel_times(source_depth_in_km=data_tr.stats.evdp,
                              distance_in_degree=data_tr.stats.gcarc,
                              phase_list=['s'+phase[0]])[0].time
        class ClickSelect(object):
            def __init__(self):
                self.key = None
                fig = plt.gcf()
                fig.canvas.mpl_connect('key_press_event', self.on_key)
            def on_key(self,event):
                self.key = event.key
                plt.close()
                return True

        gs = gridspec.GridSpec(2, 20)
        ax_bot = plt.subplot(gs[-1,:])
        ax_left = plt.subplot(gs[0,0:10])
        ax_right = plt.subplot(gs[0,10::])
        ax_right.yaxis.set_ticklabels([])
        td_full = linspace(-1*d_o,d_et-d_st-d_o,
                           num=data_tr.stats.npts)
        ts_full = linspace(-1*s_o,s_et-s_st-s_o,
                           num=synth_tr.stats.npts)
        ax_bot.plot(td_full,data_tr.data,color='k')
        ax_bot.plot(ts_full,synth_tr.data,color='r')
        ax_bot.set_xlim(time+synth_tr.stats.o-400,time+synth_tr.stats.o+400)
        ax_bot.set_ylim(data_tr.data.min()*1.4,data_tr.data.max()*1.4)
        ax_right.plot(tcs,cs,color='r')
        ax_right.plot(tcs,update_cs,color='r',ls='--')
        ax_right.plot(tcd,cd,color='k')
        ax_right.plot(tcs,roll(update_cs,int(samp*(1))),color='b',ls='--',alpha=0.3)
        ax_right.plot(tcs,roll(update_cs,int(samp*(-1))),color='g',ls='--',alpha=0.3)

        ax_left.plot(t,d,color='k')
        ax_left.plot(t,s,color='r')
        ax_left.plot(t,roll(s,int(samp*(del_t))),color='r',ls='--')
        ax_left.plot(t,roll(s,int(samp*(del_t+1))),color='b',ls='--',alpha=0.3)
        ax_left.plot(t,roll(s,int(samp*(del_t-1))),color='g',ls='--',alpha=0.3)
        ax_left.set_xlabel('Time (s)')
        ax_right.set_xlabel('Time (s)')
        ax_bot.axvline(time,color='k')
        ax_bot.axvspan(itime+synth_tr.stats.o-200,itime+synth_tr.stats.o-100,color='r',alpha=0.3)
        ax_bot.axvspan(itime+synth_tr.stats.o-100,itime+synth_tr.stats.o-50,color='g',alpha=0.3)
        ax_bot.axvspan(itime+synth_tr.stats.o-270,itime+synth_tr.stats.o-30,color='b',alpha=0.3)
        ax_bot.axvspan(time+synth_tr.stats.o+window_tuple[0],time+synth_tr.stats.o+window_tuple[1],color='k',alpha=0.2)
        ax_bot.axvline(ds_time,color='k')
        ax_bot.axvline(dp_time,color='k')

        ax_left.set_title('{} Lat:{} Lon:{} H:{}km Mw {}'.format(str(synth_tr.stats.starttime),
                                                       str(round(data_tr.stats.evla)),
                                                       str(round(data_tr.stats.evlo)),
                                                       str(round(data_tr.stats.evdp)),
                                                       str(round(data_tr.stats.mag))))
        ax_bot.set_title('Net: {} Stat: {} stla: {} stlo: {} Az: {} Gcarc: {}'.format(data_tr.stats.network,
                                                       data_tr.stats.station,
                                                       str(round(data_tr.stats.stla)),
                                                       str(round(data_tr.stats.stlo)),
                                                       str(round(data_tr.stats.az)),
                                                       str(round(data_tr.stats.gcarc))))

        clicks = ClickSelect()
        fig = plt.gcf()
        if nan_to_num(min(SNR)) < 1.5 or nan_to_num(corcoeft[1]) < 0.75 or nan_to_num(amp_rat) < 0.14:
            fig.set_facecolor('red')
        elif nan_to_num(max(SNR)) > 15000 or nan_to_num(corcoeft[1]) > 1.5 or nan_to_num(amp_rat) > 7:
            fig.set_facecolor('red')
        else:
            fig.set_facecolor('limegreen')

        plt.figtext(0.1,0.95,'press ctrl to save')
        plt.figtext(0.15,0.30,'M1: {}\nM2: {}\nS/D: {}\nSNR1: {}\nSNR2: {}\nSNR3: {}'\
                    .format(m1,m2,amp_rat,SNR[0],SNR[1],SNR[2]),size=15)
        plt.figtext(0.55,0.55,'del_t: {}s\nupdate: {}s\nfinal_t: {}s\ncorr:{}\nupdate_corr: {}'\
                    .format(del_t,update_t,del_t+update_t,corcoeft[0],corcoeft[1]),size=15)
        plt.show()
        key = clicks.key
    else:
        key = 'control'

    return tobs,corcoeft,m1,m2,update_m1,update_m2,s_amp,d_amp,del_t+update_t,key,SNR,amp_rat

def read_streams(data_pickle,synth_pickle):
    sts = obspy.read(synth_pickle)
    std = obspy.read(data_pickle)
    sts.sort(['network'])
    std.sort(['network'])
    std.differentiate()
    sts.differentiate()
    sts.interpolate(10)
    std.interpolate(10)
    return std,sts

def write_traveltime(fname,tr,tsig,tobs,corcoeft,nbt,xcl,tincore):
    idate=str(tr.stats.starttime.year)[-2::]+'%03d'%tr.stats.starttime.day
    iotime='%02d%02d%02d'%(tr.stats.starttime.hour,
                           tr.stats.starttime.minute,
                           tr.stats.starttime.second)
    ievt='1'
    kluster='0'
    stationcode=tr.stats.station
    netw=tr.stats.network
    comp=tr.stats.channel
    slat=round(tr.stats.evla,2)
    slon=round(tr.stats.evlo,2)
    sdep=round(tr.stats.evdp,2)
    rlat=round(tr.stats.stla,2)
    rlon=round(tr.stats.stlo,2)
    relev=0.0
    nobst=1
    nobsa=0
    #number of polar crossings
    kpole=0
    line_2 = '1 0 00\n'
    line_3 = '1\n'
    line_5 = '0\n'
    with open(fname,'a') as f:
        f.write('{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}\n'.format(
                str(idate),
                str(iotime),
                str(ievt),
                str(kluster),
                stationcode,
                netw,
                comp,
                str(slat),
                str(slon),
                str(sdep),
                str(rlat),
                str(rlon),
                str(relev),
                str(nobst),
                str(nobsa),
                str(kpole),
                ))
        f.write(line_2)
        f.write(line_3)
        f.write('{} {} {} {} {} {}\n'.format(
                 str(tobs),
                 str(tsig),
                 str(corcoeft[1]),
                 str(int(nbt)),
                 str(2.*xcl),
                 str(int(tincore))))
        f.write(line_5)

def write_header(phase_name,args):
    fmin = str(args.fmin)
    fmax = str(args.fmax)
    fname = getcwd().split('/')[-1]+'_'+phase_name+'.dat'
    with open(fname,'w') as f:
        f.write(fname+'\n')
        f.write('None\n')
    return fname

def write_f_resp(fname,fmin,fmax):
    fmin *= 2*pi
    fmax *= 2*pi
    b,a = butter(4,(fmin,fmax),'bandpass',analog=True)
    w,h = freqs(b, a)
    w = round(w,5)
    h = abs(round(h,5))
    freq_resp = hstack((transpose([w]),transpose([h])))
    with open(fname,'a') as f:
        f.write('1\n')
        f.write('{}\n'.format(len(w)))
        savetxt(f,freq_resp,fmt='%1.7f')

def write_branch(fname,branch_list):
    with open(fname,'a') as f:
        for ii in branch_list:
            f.write(ii+'\n')

def phase_info(phase_name):
    if phase_name == 'sSdiff':
        branch_list = ['sSdiff','sSdiff','DONT USE','DONT USE','DONT USE']
    elif phase_name == 'Sdiff':
        branch_list = ['Sdiff','Sdiff','DONT USE','DONT USE','DONT USE']
    elif phase_name == 'S':
        branch_list = ['S','S','6371 1 2','3482 2 2','6371 5 0']
    elif phase_name == 'sS':
        branch_list = ['sS','sS','6300 0 2','6371 1 2','3482 3 2','6371 5 0']

    elif phase_name == 'ScS':
        branch_list = ['ScS','ScS','6371 1 2','3482 3 2','6371 5 0']
    elif phase_name == 'ScSScS':
        branch_list = ['ScSScS','ScSScS','6371 1 2','3482 3 2','6371 3 2','3482 3 2','6371 5 0']

    elif phase_name == 'SS':
        branch_list = ['SS','SS','6371 0 2','3482 2 2','6371 3 2','3482 2 2','6371 5 0']
    elif phase_name == 'P':
        branch_list = ['S','S','6371 1 2','3482 2 2','6371 5 0']
    else:
        print('Phase name first argument')
    return branch_list

def phase_range(std,sts,phase_name):
    if phase_name == 'S' or phase_name == 'sS':

        for tr in std:
            if tr.stats.gcarc > 95.:
                std.remove(tr)
            if tr.stats.gcarc < 27.:
                std.remove(tr)
        for tr in sts:
            if tr.stats.gcarc > 95.:
                sts.remove(tr)
            if tr.stats.gcarc < 27.:
                sts.remove(tr)

    if phase_name == 'Sdiff' or phase_name == 'sSdiff':

        for tr in std:
            if tr.stats.gcarc > 150.:
                std.remove(tr)
            if tr.stats.gcarc < 105.:
                std.remove(tr)
        for tr in sts:
            if tr.stats.gcarc > 150.:
                sts.remove(tr)
            if tr.stats.gcarc < 105.:
                sts.remove(tr)

    if phase_name == 'SS' or phase_name == 'sSS':

        for tr in std:
            if tr.stats.gcarc < 56.:
                std.remove(tr)
        for tr in sts:
            if tr.stats.gcarc < 56.:
                sts.remove(tr)

    if phase_name == 'SSS' or phase_name == 'sSSS':

        for tr in std:
            if tr.stats.gcarc < 85.:
                std.remove(tr)
        for tr in sts:
            if tr.stats.gcarc < 85.:
                sts.remove(tr)

    if phase_name == 'ScS' or phase_name == 'sScS':

        for tr in std:
            if tr.stats.evdp < 200:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 25:
                    continue
                elif tr.stats.gcarc > 52 and tr.stats.gcarc < 70:
                    continue
                else:
                    std.remove(tr)
            elif tr.stats.evdp > 200 and tr.stats.evdp < 400:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 25:
                    continue
                elif tr.stats.gcarc > 52 and tr.stats.gcarc < 70:
                    continue
                else:
                    std.remove(tr)
            elif tr.stats.evdp > 400:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 31:
                    continue
                elif tr.stats.gcarc > 52 and tr.stats.gcarc < 70:
                    continue
                else:
                    std.remove(tr)

        for tr in sts:
            if tr.stats.evdp < 200:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 25:
                    continue
                elif tr.stats.gcarc > 52 and tr.stats.gcarc < 70:
                    continue
                else:
                    sts.remove(tr)
            elif tr.stats.evdp > 200 and tr.stats.evdp < 400:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 25:
                    continue
                elif tr.stats.gcarc > 52 and tr.stats.gcarc < 70:
                    continue
                else:
                    sts.remove(tr)
            elif tr.stats.evdp > 400:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 31:
                    continue
                elif tr.stats.gcarc > 52 and tr.stats.gcarc < 70:
                    continue
                else:
                    sts.remove(tr)

    if phase_name == 'ScSScS' or phase_name == 'sScSScS':

        for tr in std:
            if tr.stats.evdp < 200:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 60:
                    continue
                elif tr.stats.gcarc > 96 and tr.stats.gcarc < 160:
                    continue
                else:
                    std.remove(tr)
            elif tr.stats.evdp > 200 and tr.stats.evdp < 400:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 60:
                    continue
                elif tr.stats.gcarc > 96 and tr.stats.gcarc < 160:
                    continue
                else:
                    std.remove(tr)
            elif tr.stats.evdp > 400:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 73:
                    continue
                elif tr.stats.gcarc > 96 and tr.stats.gcarc < 160:
                    continue
                else:
                    std.remove(tr)

        for tr in sts:
            if tr.stats.evdp < 200:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 60:
                    continue
                elif tr.stats.gcarc > 96 and tr.stats.gcarc < 160:
                    continue
                else:
                    sts.remove(tr)
            elif tr.stats.evdp > 200 and tr.stats.evdp < 400:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 60:
                    continue
                elif tr.stats.gcarc > 96 and tr.stats.gcarc < 160:
                    continue
                else:
                    sts.remove(tr)
            elif tr.stats.evdp > 400:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 73:
                    continue
                elif tr.stats.gcarc > 96 and tr.stats.gcarc < 160:
                    continue
                else:
                    sts.remove(tr)

    if phase_name == 'ScSScSScS' or phase_name == 'sScSScSScS':

        for tr in std:
            if tr.stats.evdp < 200:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 90:
                    continue
                else:
                    std.remove(tr)
            elif tr.stats.evdp > 200 and tr.stats.evdp < 400:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 90:
                    continue
                else:
                    std.remove(tr)
            elif tr.stats.evdp > 400:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 120:
                    continue
                else:
                    std.remove(tr)

        for tr in sts:
            if tr.stats.evdp < 200:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 90:
                    continue
                else:
                    sts.remove(tr)
            elif tr.stats.evdp > 200 and tr.stats.evdp < 400:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 90:
                    continue
                else:
                    sts.remove(tr)
            elif tr.stats.evdp > 400:
                if tr.stats.gcarc > 2. and tr.stats.gcarc < 120:
                    continue
                else:
                    sts.remove(tr)

    if phase_name == 'SKS':
        for tr in std:
            if tr.stats.gcarc > 85 and tr.stats.gcarc < 135:
                continue
            else:
                std.remove(tr)
        for tr in sts:
            if tr.stats.gcarc > 85 and tr.stats.gcarc < 135:
                continue
            else:
                sts.remove(tr)

    if phase_name == 'SKKS':
        for tr in std:
            if tr.stats.gcarc > 110 and tr.stats.gcarc < 140:
                continue
            else:
                std.remove(tr)
        for tr in sts:
            if tr.stats.gcarc > 110 and tr.stats.gcarc < 140:
                continue
            else:
                sts.remove(tr)

    if phase_name == 'P' or phase_name == 'pP':

        for tr in std:
            if tr.stats.gcarc > 98.:
                std.remove(tr)
            if tr.stats.gcarc < 27.:
                std.remove(tr)
        for tr in sts:
            if tr.stats.gcarc > 98.:
                sts.remove(tr)
            if tr.stats.gcarc < 27.:
                sts.remove(tr)

    if phase_name == 'Pdiff' or phase_name == 'pPdiff':

        for tr in std:
            if tr.stats.gcarc < 100.:
                std.remove(tr)
            if tr.stats.gcarc > 150.:
                std.remove(tr)
        for tr in sts:
            if tr.stats.gcarc < 100.:
                sts.remove(tr)
            if tr.stats.gcarc > 150.:
                sts.remove(tr)

    if phase_name == 'PP' or phase_name == 'pPP':

        for tr in std:
            if tr.stats.gcarc < 56.:
                std.remove(tr)
        for tr in sts:
            if tr.stats.gcarc < 56.:
                sts.remove(tr)

    if phase_name == 'PPP' or phase_name == 'pPPP':

        for tr in std:
            if tr.stats.gcarc < 85.:
                std.remove(tr)
        for tr in sts:
            if tr.stats.gcarc < 85.:
                sts.remove(tr)

    if phase_name == 'PKP' or phase_name == 'pPKP':

        for tr in std:
            if tr.stats.gcarc < 140.:
                std.remove(tr)
        for tr in sts:
            if tr.stats.gcarc < 140.:
                sts.remove(tr)

    return std,sts

def write_amp_header(phase_name,fmin,fmax):
    fname = getcwd().split('/')[-1]+'_'+phase_name+'_amp.dat'
    with open(fname,'w') as f:
        f.write(fname+'\n')
        f.write('fmin,fmax''\n')
        f.write('{} {}\n'.format(fmin,fmax))
        f.write('idate,iotime,stat,netw,comp,slat,slon,sdep,rlat,rlon,relev,tobs,delt,corcoeft,m1,m2,s_amp,d_amp,SNR1,SNR2,SNR3,amp_rat\n')
    return fname

def write_amplitude(fname,ii,tr,tobs,corcoeft,m1,m2,update_m1,update_m2,s_amp,d_amp,del_t,SNR,amp_rat):
    idate=str(tr.stats.starttime.year)[-2::]+'%03d'%tr.stats.starttime.day
    iotime='%02d%02d%02d'%(tr.stats.starttime.hour,
                           tr.stats.starttime.minute,
                           tr.stats.starttime.second)
    stationcode=tr.stats.station
    netw=tr.stats.network
    comp=tr.stats.channel
    slat=round(tr.stats.evla,2)
    slon=round(tr.stats.evlo,2)
    sdep=round(tr.stats.evdp,2)
    rlat=round(tr.stats.stla,2)
    rlon=round(tr.stats.stlo,2)
    relev=0.0
    #number of polar crossings
    line_2 = '1 0 00\n'
    line_3 = '1\n'
    line_5 = '0\n'
    with open(fname,'a') as f:
        f.write('{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}\n'.format(
                str(ii),
                str(idate),
                str(iotime),
                '%5s'%stationcode,
                '%3s'%netw,
                '%3s'%comp,
                '%1.2f'%slat,
                '%1.2f'%slon,
                '%1.1f'%sdep,
                '%1.1f'%rlat,
                '%1.1f'%rlon,
                '%1.2f'%relev,
                '%1.1f'%tobs,
                '%1.1f'%del_t,
                '%1.3f'%corcoeft[0],
                '%1.3f'%corcoeft[1],
                '%1.3f'%m1,
                '%1.3f'%m2,
                '%1.3f'%update_m1,
                '%1.3f'%update_m2,
                '%1.2e'%s_amp,
                '%1.2e'%d_amp,
                '%1.2f'%SNR[0],
                '%1.2f'%SNR[1],
                '%1.2f'%SNR[2],
                '%1.2f'%amp_rat,
                ))

def monochrome(tt,yy):
    '''
    Find likliest frequency
    '''
    #tt = np.linspace(0,tr.stats.endtime-tr.stats.starttime,num=tr.stats.npts)
    #yy = tr.data
    ff = fftfreq(len(tt),(tt[1]-tt[0]))
    Fyy = abs(fft(yy))
    freq = abs(ff[argmax(Fyy[1:])+1])
    return freq

main()

